import {
  MdAccountBalance,
  MdAdd,
  MdAdminPanelSettings,
  MdApartment,
  MdArrowBack,
  MdArrowForward,
  MdAssignmentTurnedIn,
  MdAttachFile,
  MdBadge,
  MdBlock,
  MdCalendarMonth,
  MdCampaign,
  MdCancel,
  MdCheck,
  MdCheckCircle,
  MdChevronLeft,
  MdChevronRight,
  MdClose,
  MdDashboard,
  MdDelete,
  MdDeleteForever,
  MdDeveloperMode,
  MdDescription,
  MdDiversity3,
  MdDownload,
  MdEdit,
  MdEditCalendar,
  MdEditNote,
  MdErrorOutline,
  MdEventAvailable,
  MdEventBusy,
  MdExpandLess,
  MdExpandMore,
  MdFactCheck,
  MdFilterList,
  MdGroupAdd,
  MdGroups,
  MdHelp,
  MdHelpOutline,
  MdHowToReg,
  MdHub,
  MdLocationOn,
  MdLock,
  MdLogout,
  MdMail,
  MdManageAccounts,
  MdMedicalServices,
  MdMeetingRoom,
  MdMenu,
  MdMoreVert,
  MdNotifications,
  MdOpenInNew,
  MdPayments,
  MdPerson,
  MdPersonAdd,
  MdPersonOff,
  MdPhotoCamera,
  MdPictureAsPdf,
  MdPlayArrow,
  MdPrint,
  MdRateReview,
  MdReceiptLong,
  MdSave,
  MdSchedule,
  MdSchool,
  MdSearch,
  MdSelectAll,
  MdSend,
  MdWorkspacePremium,
  MdSettings,
  MdShoppingBag,
  MdStopCircle,
  MdTaskAlt,
  MdTimer,
  MdUploadFile,
  MdVerified,
  MdVerifiedUser,
  MdVideocam,
  MdVisibility,
  MdVisibilityOff,
  MdZoomIn,
} from "react-icons/md";

/**
 * Registry icon global aplikasi.
 *
 * Seluruh komponen memakai nama icon berbentuk snake_case agar UI tidak
 * bergantung langsung pada nama export dari react-icons.
 */
const iconRegistry = {
  add: MdAdd,
  admin_panel_settings: MdAdminPanelSettings,
  apartment: MdApartment,
  arrow_back: MdArrowBack,
  arrow_forward: MdArrowForward,
  assignment_turned_in: MdAssignmentTurnedIn,
  attach_file: MdAttachFile,
  badge: MdBadge,
  block: MdBlock,
  calendar_month: MdCalendarMonth,
  campaign: MdCampaign,
  delete_forever: MdDeleteForever,
  diversity_3: MdDiversity3,
  cancel: MdCancel,
  check: MdCheck,
  check_circle: MdCheckCircle,
  chevron_left: MdChevronLeft,
  chevron_right: MdChevronRight,
  close: MdClose,
  dashboard: MdDashboard,
  delete: MdDelete,
  developer_mode: MdDeveloperMode,
  description: MdDescription,
  download: MdDownload,
  edit: MdEdit,
  edit_calendar: MdEditCalendar,
  edit_note: MdEditNote,
  error_outline: MdErrorOutline,
  event_available: MdEventAvailable,
  event_busy: MdEventBusy,
  // Alias UI: memakai MdEventAvailable karena react-icons/md tidak memiliki MdEventUpcoming.
  event_upcoming: MdEventAvailable,
  expand_less: MdExpandLess,
  expand_more: MdExpandMore,
  fact_check: MdFactCheck,
  filter_list: MdFilterList,
  group_add: MdGroupAdd,
  groups: MdGroups,
  help: MdHelp,
  help_outline: MdHelpOutline,
  hub: MdHub,
  how_to_reg: MdHowToReg,
  location_on: MdLocationOn,
  lock: MdLock,
  lock_person: MdAdminPanelSettings,
  logout: MdLogout,
  mail: MdMail,
  manage_accounts: MdManageAccounts,
  medical_services: MdMedicalServices,
  meeting_room: MdMeetingRoom,
  menu: MdMenu,
  more_vert: MdMoreVert,
  notifications: MdNotifications,
  open_in_new: MdOpenInNew,
  payments: MdPayments,
  person: MdPerson,
  person_add: MdPersonAdd,
  person_off: MdPersonOff,
  photo_camera: MdPhotoCamera,
  picture_as_pdf: MdPictureAsPdf,
  play_arrow: MdPlayArrow,
  print: MdPrint,
  rate_review: MdRateReview,
  receipt: MdReceiptLong,
  receipt_long: MdReceiptLong,
  save: MdSave,
  schedule: MdSchedule,
  school: MdSchool,
  search: MdSearch,
  select_all: MdSelectAll,
  send: MdSend,
  settings: MdSettings,
  shopping_bag: MdShoppingBag,
  stop_circle: MdStopCircle,
  workspace_premium: MdWorkspacePremium,
  task_alt: MdTaskAlt,
  timer: MdTimer,
  upload_file: MdUploadFile,
  verified: MdVerified,
  verified_user: MdVerifiedUser,
  videocam: MdVideocam,
  visibility: MdVisibility,
  visibility_off: MdVisibilityOff,
  zoom_in: MdZoomIn,
};

export default function AppIcon({
  name,
  size = 20,
  className = "",
  title,
}) {
  const Icon = iconRegistry[name];

  if (!Icon) {
    if (process.env.NODE_ENV === "development") {
      console.warn(`[AppIcon] Icon "${name}" belum terdaftar.`);
    }

    return null;
  }

  return (
    <Icon
      size={size}
      className={className}
      aria-hidden={title ? undefined : "true"}
      aria-label={title}
      title={title}
      focusable="false"
    />
  );
}